### ISSUE TITLE
Bring documentation up to date

### ISSUE THREAD

**Issue by desilinguist** [EducationalTestingService/skll#459]
Before releasing v2.0, we need to make sure that the documentation is fully up to date:

- [x] Remove reference to `objective` field

- [x] Remove any reference to default values for `objectives`.

- [x] Make sure we talk about how `objectives` is now required for grid search and `metrics` is now required for learning curves. Make sure this discussion includes the fact that the default values in the API now conflict but we are okay with that because of X,Y, Z benefits. See PR #462 for a discussion.

- [x] Add `--no_labels` to `skll_convert` documentation and anything else that's needed about unlabeled data. 

- [x] Talk about feature hashing and how it applies in the case when the features in a set are spread across multiple files on disk.

- [x] Talk about `grid_search` being set to `True` by default for config files when it was `False` previously.

- [x] Make sure all documentation about `results` directories/files for tasks is up to date after PR #471. Changes have been made such that a results path is now allowed for the `train` and `predict` tasks when grid search is `true`. The JSON results file will now include grid search CV results. In a couple cases, these results could be `null` (when reusing an existing model via the `-k` option or when the parameter grid is empty). See more discussion on this in the referenced PR.

- [x] Talk about how `print_model_weights` works for hashed features.

- [x] Update `Contributing.md` to have the correct `conda` command to install the requirements.

- [x] Talk about switching to `pandas` for reading and writing and the pros and cons.

- [x] Check if any of the things we changed from deprecation warnings to errors need to be updated in the documentation as well.

- [x] Document `--sort_by_labels` for `print_model_weights`.

- [x] Update documentation for metrics/objectives computation.

- [x] Update documentation for logs to say that it also captures scikit-learn warnings.

- [x] Update documentation to remove references to Python 2.7.

- [x] Make sure to mention that `pandas` and `seaborn` are direct dependencies.  And that `tabulate` has replaced `prettytable`.

- [x] Document bugfix in `generate_predictions`

- [x] Fix config file in README.

- [x] Document various fixes in #473 , #472, #444.

- [x] Document that grid search is `True` by default for both API and config file.

- [x] Document that CV models can be saved now.

*Note*: This issue should be updated as other issues are closed. It's probably better to have a single PR to update the documentation and have it reviewed at once.

**Comment by desilinguist** [comment]
Addressed by #568
